#!/usr/bin/php -d mysqlnd.net_read_timeout=3600
<?php
set_include_path("../../../include");
require("header.inc.php");

$startShard = !empty($argv[1]) ? $argv[1] : 1;
$shardIDs = Zotero_DB::columnQuery("SELECT shardID FROM shards WHERE shardID >= ? ORDER BY shardID", $startShard);

foreach ($shardIDs as $shardID) {
	echo "Shard: $shardID\n";
	Zotero_DB::query("UPDATE itemFulltext IFT JOIN items I USING (itemID) SET IFT.libraryID=I.libraryID", false, $shardID);
	Zotero_Admin_DB::query("ALTER TABLE `itemFulltext` ADD INDEX `libraryVersion` (`libraryID`, `version`)", false, $shardID);
}
