#!/usr/bin/php -d mysqlnd.net_read_timeout=3600
<?php
set_include_path("../../../include");
require("header.inc.php");

$startShard = !empty($argv[1]) ? $argv[1] : 1;
$shardIDs = Zotero_DB::columnQuery("SELECT shardID FROM shards WHERE shardID >= ? ORDER BY shardID", $startShard);

foreach ($shardIDs as $shardID) {
	echo "Shard: $shardID\n";
	Zotero_Admin_DB::query("ALTER TABLE `itemCreators` DROP FOREIGN KEY `itemCreators_ibfk_2`", false, $shardID);
	Zotero_Admin_DB::query("ALTER TABLE `creators` CHANGE `creatorID` `creatorID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT", false, $shardID);
	Zotero_Admin_DB::query("ALTER TABLE `itemCreators` CHANGE `creatorID` `creatorID` BIGINT UNSIGNED NOT NULL", false, $shardID);
	Zotero_Admin_DB::query("ALTER TABLE `itemCreators` ADD CONSTRAINT `itemCreators_ibfk_2` FOREIGN KEY (`creatorID`) REFERENCES `creators` (`creatorID`) ON DELETE CASCADE", false, $shardID);
}
