#!/usr/bin/php -d mysqlnd.net_read_timeout=3600
<?php
set_include_path("../../../include");
require("header.inc.php");

Zotero_Admin_DB::query("ALTER TABLE `keyPermissions` ADD INDEX (`libraryID`)");
