#!/usr/local/bin/php -d mysqlnd.net_read_timeout=86400
<?php
set_include_path("../../../include");
require("header.inc.php");

$shardHostID = $argv[1];
$startShard = $argv[2];
$stopShard = $argv[3];

Z_Core::$debug = true;

$shardIDs = Zotero_DB::columnQuery("SELECT shardID FROM shards WHERE shardHostID=? AND shardID >= ? AND shardID <= ? ORDER BY shardID", [$shardHostID, $startShard, $stopShard]);
foreach ($shardIDs as $shardID) {
	echo "Shard: $shardID\n";

	echo "Setting shard to readonly\n";
	Zotero_DB::query("UPDATE shards SET state='readonly' WHERE shardID=?", $shardID);
	
	echo "Waiting 60 seconds for requests to stop\n";
	sleep(60);
	
	// Drop foreign key constraint
	Zotero_Admin_DB::query("ALTER TABLE `itemCreators` DROP CONSTRAINT `itemCreators_ibfk_1`;", false, $shardID);
	Zotero_Admin_DB::query("ALTER TABLE `itemCreators` DROP CONSTRAINT `itemCreators_ibfk_2`;", false, $shardID);

	// Rename old itemCreators table
	Zotero_Admin_DB::query("RENAME TABLE itemCreators TO itemCreatorsOld;", false, $shardID);

	// Create new itemCreators table
	Zotero_Admin_DB::query("CREATE TABLE `itemCreators` ( `creatorID` BIGINT UNSIGNED NOT NULL, `itemID` BIGINT UNSIGNED NOT NULL, `firstName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL, `lastName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL, `fieldMode` tinyint(1) UNSIGNED DEFAULT NULL, `creatorTypeID` smallint(5) UNSIGNED NOT NULL, `orderIndex` smallint(5) UNSIGNED NOT NULL, PRIMARY KEY (`creatorID`, `itemID`), KEY `creatorTypeID` (`creatorTypeID`), KEY `name` (`lastName`(7),`firstName`(6)) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;", false, $shardID);

	// Add foreign key to item constraint
	Zotero_Admin_DB::query("ALTER TABLE `itemCreators` ADD CONSTRAINT `itemCreators_ibfk_1` FOREIGN KEY (`itemID`) REFERENCES `items` (`itemID`) ON DELETE CASCADE;", false, $shardID);

	// Populate new table with data
	Zotero_Admin_DB::query("INSERT INTO itemCreators (creatorID, firstName, lastName, fieldMode, itemID, creatorTypeID, orderIndex ) SELECT creatorID, firstName, lastName, fieldMode, itemID, creatorTypeID, orderIndex from creators INNER JOIN itemCreatorsOld USING (creatorID);", false, $shardID);

	// Drop old creators tables
	Zotero_Admin_DB::query("DROP TABLE itemCreatorsOld;", false, $shardID);
	Zotero_Admin_DB::query("DROP TABLE creators;", false, $shardID);

	echo "Bringing shard back up\n";
	Zotero_DB::query("UPDATE shards SET state='up' WHERE shardID=?;", $shardID);
	echo "Done with shard $shardID\n\n";
	sleep(1);
}
