#!/usr/bin/php -d mysqlnd.net_read_timeout=3600
<?php
set_include_path("../../../include");
require("header.inc.php");

// Run this before rolling out code changes
Zotero_Admin_DB::query("ALTER TABLE `libraries` ADD `hasData` TINYINT( 1 ) NOT NULL DEFAULT '0' AFTER `version` , ADD INDEX ( `hasData` )");
Zotero_DB::query("UPDATE `libraries` SET hasData=1 WHERE version > 0 OR lastUpdated != '0000-00-00 00:00:00'");
