#!/usr/bin/php -d mysqlnd.net_read_timeout=3600
<?php
set_include_path("../../../include");
require("header.inc.php");

Zotero_DB::query("ALTER TABLE libraries ADD COLUMN deindexed_from_es tinyint(1) unsigned NOT NULL DEFAULT '0';");