#!/usr/bin/php -d mysqlnd.net_read_timeout=3600
<?
set_include_path("../../../include");
require("header.inc.php");

$startShard = !empty($argv[1]) ? $argv[1] : 1;

$shardIDs = Zotero_DB::columnQuery("SELECT shardID FROM shards WHERE shardID >= ? ORDER BY shardID", $startShard);
foreach ($shardIDs as $shardID) {
	echo "Shard: $shardID\n";
	
	$affectedRows = Zotero_DB::query("DELETE FROM itemData WHERE value IS NULL", false, $shardID);
	echo "Deleted $affectedRows row(s)\n";
}
