#!/usr/bin/php -d mysqlnd.net_read_timeout=3600
<?
set_include_path("../../../include");
require("header.inc.php");

Zotero_Admin_DB::query("ALTER TABLE `groups` CHANGE `description` `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL");
